### ISSUE TITLE
general contribution questions

### ISSUE THREAD

**Issue by stbischof** [tjwatson/atomos#11]
Is it okay to change to Junit5?
Are there codestyles/formatter rules that should be used?
Interested in automatic test/ [github workflows](https://github.com/stbischof/atomos/actions) ?
Is org.atomos the final package/domain or just a temporary project?

**Comment by tjwatson** [comment]
I'll answer the last question first, because it impacts the rest of the answers.

This project started out as a proof of concept to prove the design of the OSGI Connect specification that is in progress at the OSGi alliance.  That specification process is proceedingly nicely and I think the initial goals of the Atomos project have been accomplished.  Going forward I intend to contribute the Atomos project to the Apache Felix project.  Assuming that contribution process gets accepted by the Apache Felix project it will impact some of the names.  I'm going to try and keep the name Atomos, but the package names will need to move to under the org.apache.felix domain.  It also means I need to change the license from Eclipse to Apache, which I plan to do shortly and before I make a proposal to contribute to Apache Felix.

Right now I have not set up a defined set of codestyles/formatter rules.  That will eventually change to use the style/formatter rules of the Apache Felix project.

I think changing to Junit 5 is fine, assuming Junit 5 can still run on Java 8.  I do want to keep a minimum Java 8 requirement for now.

How can I turn down the github workflows?  Unfortunately I don't think the Apache Felix project has any projects with similar workflows, but I think what you did there looks very useful for a real project.  I'll have to see if something similar can be done when hosting the project within Apache Felix.

**Comment by tjwatson** [comment]
The github workflow for running Java CI has been added as well as the badge for status in the readme.
